version: 2.1
executors:
  node10:
    docker:
      - image: circleci/node:10

commands:
  restore_cache_checkout:
    steps:
      - restore_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}

  run_checkout:
    steps:
      - checkout
      - save_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
  run_yarn:
    steps:
      - restore_cache:
          keys:
            - v1-yarn-{{ .Branch }}
      - run:
          name: yarn install
          command: yarn install --no-progress --non-interactive --cache-folder ~/.cache/yarn
      - save_cache:
          paths:
            - node_modules
            - ~/.cache/yarn
          key: v1-yarn-{{ .Branch }}

jobs:
  # Checkout code and caches it
  setup:
    executor: node10
    working_directory: ~/versions-diff-web
    steps:
      - checkout
      - save_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/versions-diff-web

  # Run lint and tests
  test:
    executor: node10
    working_directory: ~/versions-diff-web

    steps:
      - restore_cache_checkout
      - run_yarn
      - run: yarn run lint
      - run: yarn run test --runInBand

  # Deploy website to GitHub Pages
  deploy:
    executor: node10
    working_directory: ~/versions-diff-web
    steps:
      - restore_cache_checkout
      - run_yarn
      - run:
          name: Build
          command: yarn build
      - run:
          name: Deploy
          command: |
            if [[ $CIRCLE_PROJECT_USERNAME == "react-native-community" ]]; then
              git config --global user.email $GH_EMAIL
              git config --global user.name $GH_NAME

              yarn gh-pages -d build --message "[skip ci] Updates" --repo https://$GH_TOKEN@github.com/blitz-js/versions-diff-web.git
            else
              echo "Skipping deploy."
            fi

workflows:
  version: 2.1
  tests:
    jobs:
      - setup

      - test:
          requires:
            - setup
  deploy-to-gh-pages:
    jobs:
      - setup:
          filters:
            branches:
              only:
                - master
              # Forked pull requests have `CIRCLE_BRANCH` set to pull/XXX
              ignore: /pull\/[0-9]+/

      - deploy:
          requires:
            - setup
